[project]
name = "doentes-uq-bd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.7",
    "pydantic-ai[logfire]>=0.0.20",
    "pymongo>=4.10.1",
    "uvicorn>=0.34.0",
]
